stages:
  - build
  - test
  - deploy

.build:
  stage: build
  image: node:8.15-jessie
  script:
    - yarn && yarn build --environment=$ENVIRONMENT
    - STORYBOOK_ENV=$ENVIRONMENT yarn build-storybook
    - mv storybook-static build
  cache:
    paths:
      - node_modules/
    key: node_cache
  artifacts:
    paths:
      - build
    expire_in: 1 hour
  tags:
    - aws-runner

.test:
  stage: test
  image: node:8.15-jessie
  script:
    - yarn && yarn test --coverage
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - coverage
  tags:
    - aws-runner

.deploy:
  stage: deploy
  image: amazon/aws-cli
  script:
    - aws s3 sync --delete build/ s3://$BUCKET
  tags:
    - aws-runner

### STAGING ENVIRONMENT ###
build_staging:
  extends: .build
  environment: staging
  before_script:
    - apt-get update && apt-get install -yq gettext-base
    - envsubst < ./config/environments/staging.tpl.js > ./config/environments/staging.js
  only:
    - stage

test_staging:
  stage: test
  extends: .test
  environment: staging
  only:
    - stage

deploy_staging:
  extends: .deploy
  environment: staging
  variables:
    AWS_ACCESS_KEY_ID: $DEV_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $DEV_AWS_SECRET_ACCESS_KEY
    BUCKET: $STAGING_BUCKET
  only:
    - stage
### END OF STAGING ENVIRONMENT ###


### PROD ENVIRONMENT ###
build_production:
  extends: .build
  environment: production
  only:
    - master

test_production:
  stage: test
  extends: .test
  environment: production
  only:
    - master
    
deploy_production:
  stage: deploy
  extends: .deploy
  environment: production
  variables:
    AWS_ACCESS_KEY_ID: $PROD_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $PROD_AWS_SECRET_ACCESS_KEY
    BUCKET: $PROD_BUCKET
  only:
    - master
### END OF PROD ENVIRONMENT ###