stages:
  - build
  - test
  - deploy

.build:
  stage: build
  image: node:8.15-jessie
  script:
    - yarn && yarn build --environment=$ENVIRONMENT
    - STORYBOOK_ENV=$ENVIRONMENT yarn build-storybook
    - mv storybook-static build
  cache:
    paths:
      - node_modules/
    key: node_cache
  artifacts:
    paths:
      - build
    expire_in: 1 hour
  tags:
    - aws-runner

.test:
  stage: test
  image: node:8.15-jessie
  script:
    - yarn && yarn test --coverage
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - coverage
  tags:
    - aws-runner

.deploy:
  stage: deploy
  image: python:latest
  script:
    - pip install awscli
    - aws s3 sync --delete build/ s3://$BUCKET
  tags:
    - aws-runner

build_staging:
  extend: .build
  environment: staging
  before_script:
    - apt-get update && apt-get install -yq gettext-base
    - envsubst < ./config/environments/staging.tpl.js > ./config/environments/staging.js
  only:
    - stage

test_staging:
  stage: test
  extend: .test
  environment: staging
  only:
    - stage

deploy_staging:
  extend: .deploy
  environment: staging
  variables:
    AWS_ACCESS_KEY_ID: $DEV_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $DEV_AWS_SECRET_ACCESS_KEY
    BUCKET: $STAGING_BUCKET
  only:
    - stage

build_production:
  extend: .build
  environment: production
  script:
    - yarn && yarn build --environment=production
  cache:
    paths:
      - node_modules/
    key: node_cache
  artifacts:
    paths:
      - build
    expire_in: 1 hour
  only:
    - stage

deploy_production:
  environment: production
  variables:
    AWS_ACCESS_KEY_ID: $PROD_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $PROD_AWS_SECRET_ACCESS_KEY
    BUCKET: $PROD_BUCKET
  only:
    - master

